# Generated by Django 3.1.5 on 2021-05-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ordertransaction',
            managers=[
            ],
        ),
    ]
